name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Add .env file to server
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          scp -i ec2_key.pem -o StrictHostKeyChecking=no .env ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/2-giveYouEar-SpeekSee-BE/.env

      - name: Deploy to EC2 with systemd
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/2-giveYouEar-SpeekSee-BE
            git pull origin main

            ./gradlew build -x test

            sudo systemctl daemon-reload
            sudo systemctl restart speeksee
            sudo systemctl status speeksee --no-pager
          EOF
